{% set version = "0.18.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjstats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sjstats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjstats/sjstats_{{ version }}.tar.gz
  sha256: 6a526eb940c3f8ab15ea03b892577c40a80861dcf19fe23a8cd8406fa50768b3

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bayestestr >=0.4.0
    - r-broom
    - r-dplyr >=0.8.1
    - r-effectsize
    - r-emmeans
    - r-insight >=0.8.0
    - r-lme4
    - r-magrittr
    - r-mass
    - r-modelr
    - r-parameters >=0.4.0
    - r-performance >=0.4.0
    - r-purrr
    - r-rlang
    - r-sjlabelled >=1.1.1
    - r-sjmisc >=2.8.2
    - r-tidyr
  run:
    - r-base
    - r-bayestestr >=0.4.0
    - r-broom
    - r-dplyr >=0.8.1
    - r-effectsize
    - r-emmeans
    - r-insight >=0.8.0
    - r-lme4
    - r-magrittr
    - r-mass
    - r-modelr
    - r-parameters >=0.4.0
    - r-performance >=0.4.0
    - r-purrr
    - r-rlang
    - r-sjlabelled >=1.1.1
    - r-sjmisc >=2.8.2
    - r-tidyr

test:
  commands:
    - $R -e "library('sjstats')"           # [not win]
    - "\"%R%\" -e \"library('sjstats')\""  # [win]

about:
  home: https://github.com/strengejacke/sjstats, https://strengejacke.github.io/sjstats
  license: GPL-3.0-only
  summary: Collection of convenient functions for common statistical computations, which are not directly provided by R's base or stats packages. This package aims at providing, first, shortcuts for statistical measures,  which otherwise could only be calculated with additional effort  (like Cramer's V, Phi, or effect size
    statistics like Eta or Omega squared),  or for which currently no functions available. Second, another focus  lies on weighted variants of common statistical measures and tests  like weighted standard error, mean, t-test, correlation, and more.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ccwang002

# Package: sjstats
# Type: Package
# Encoding: UTF-8
# Title: Collection of Convenient Functions for Common Statistical Computations
# Version: 0.17.6
# Date: 2019-09-08
# Authors@R: person("Daniel", "Ludecke", role = c("aut", "cre"), email = "d.luedecke@uke.de", comment = c(ORCID = "0000-0002-8895-3206"))
# Maintainer: Daniel Ludecke <d.luedecke@uke.de>
# Description: Collection of convenient functions for common statistical computations, which are not directly provided by R's base or stats packages. This package aims at providing, first, shortcuts for statistical measures,  which otherwise could only be calculated with additional effort  (like Cramer's V, Phi, or effect size statistics like Eta or Omega squared),  or for which currently no functions available. Second, another focus  lies on weighted variants of common statistical measures and tests  like weighted standard error, mean, t-test, correlation, and more.
# License: GPL-3
# Depends: R (>= 3.2)
# Imports: bayestestR (>= 0.2.5), broom, dplyr (>= 0.8.1), emmeans, insight (>= 0.4.1), lme4, magrittr, MASS, modelr, parameters (>= 0.1.0), performance (>= 0.3.0), purrr, rlang, sjlabelled (>= 1.1.0), sjmisc (>= 2.8.1), stats, tidyr, utils
# Suggests: brms, car, coin, ggplot2, graphics, httr, knitr, mediation, nlme, pbkrtest (>= 0.4-7), pscl, pwr, sandwich, sjPlot, survey, rstan, rstanarm, VGAM, Zelig, testthat
# URL: https://github.com/strengejacke/sjstats, https://strengejacke.github.io/sjstats
# BugReports: https://github.com/strengejacke/sjstats/issues
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-09-08 16:51:16 UTC; Daniel
# Author: Daniel Ludecke [aut, cre] (<https://orcid.org/0000-0002-8895-3206>)
# Repository: CRAN
# Date/Publication: 2019-09-08 22:00:03 UTC
