{% set version = '0.17.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sjstats
  version: {{ version|replace("-", "_") }}

source:
  fn: sjstats_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sjstats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sjstats/sjstats_{{ version }}.tar.gz
  sha256: 99081819731da4c6da3ef7e20b335f5e9e47b5f3413e7021f539e5637719ef30

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-bayesplot
    - r-broom >=0.4.5    
    - r-coin
    - r-crayon
    - r-dplyr
    - r-emmeans
    - r-lme4
    - r-glmmtmb >=0.2.2.0
    - r-magrittr
    - r-mass
    - r-matrix
    - r-modelr
    - r-nlme
    - r-purrr
    - r-pwr
    - r-rlang
    - r-sjlabelled >=1.0.14
    - r-sjmisc >=2.7.5
    - r-tidyr
  run:
    - r-base
    - r-bayesplot
    - r-broom >=0.4.5    
    - r-coin
    - r-crayon
    - r-dplyr
    - r-emmeans
    - r-lme4
    - r-glmmtmb >=0.2.2.0
    - r-magrittr
    - r-mass
    - r-matrix
    - r-modelr
    - r-nlme
    - r-purrr
    - r-pwr
    - r-rlang
    - r-sjlabelled >=1.0.14
    - r-sjmisc >=2.7.5
    - r-tidyr

test:
  commands:
    - $R -e "library('sjstats')"           # [not win]
    - "\"%R%\" -e \"library('sjstats')\""  # [win]

about:
  home: https://github.com/strengejacke/sjstats, https://strengejacke.github.io/sjstats
  license: GPL-3
  summary: Collection of convenient functions for common statistical computations, which are
    not directly provided by R's base or stats packages. This package aims at providing,
    first, shortcuts for statistical measures, which otherwise could only be calculated
    with additional effort (like standard errors or root mean squared errors). Second,
    these shortcut functions are generic (if appropriate), and can be applied not only
    to vectors, but also to other objects as well (e.g., the Coefficient of Variation
    can be computed for vectors, linear models, or linear mixed models; the r2()-function
    returns the r-squared value for 'lm', 'glm', 'merMod' and other model objects).
    The focus of most functions lies on summary statistics or fit measures for regression
    models, including generalized linear models, mixed effects models and Bayesian models.
    However, some  of the functions also deal with other statistical measures,  like
    Cronbach's Alpha, Cramer's V, Phi etc.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - ccwang002
