appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gBZaoSypMZt6kTdwPidbiTwgNUTiJbUPJN2b1cB9Com/q8TwukA8LAWAXy4LdymmveB/LvB1pt/MlqqnrpMTKxBnU3mGqkwrB3O9qdC+Ia738VEx/ML0eBCGaoLaz4i698E7wYeURYr9+ZNhVe2VEk0v+ltV9let5Gwgz4E35SEYXslfXsQdF43cDA2hnQE7Vc1YcvxJixMR1wkBRmyhbmdFGJphhY9+QnaylzinImvKt8fzWgwz1u/gY0b6W0jdEf17M2Gz4q2P0ibJDACHlokCUMC4koPy/qt44iItoE/+W1hqh4spZOTZdAdfHexkiC+a6XsSyde/vAb+Bbe81FlQZ1N+AyUp2eGhqgboG7Alri9tHAYGLhSGgA20ISDGHH9qQuzyWROGQS6XLD197/WOyEwu8SWNGDP4kYJxv4/67iRX1O8b1UR5GByag5SVWSQr/4e1bGoEf9zfBoYYonKHoVoWXWUVLBbeRFN6FSzaUsmHJzlqWUswbIPpy39tvmu4g9Tw2nO41lBqtq7KuAerpVkMzc1X7ZaloY7jndFn3WyE97BppLLkR8t9MQD0pbROYk33VcX73/9myKCK2dpYn6s5QH9UkOxv6hHuZqFTeZWZtOLpO5YD1E/E15zhFMC0+I8r6kPr+qKTRkjdRBrfyT4CpJGeHBwkCqjgBYo=
conda_forge_output_validation: false
